# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath F:/yingjian/modelsim/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/yingjian/verilog/book/theMainDesign/myKeyBoard/myKeyBoard.cache/wt [current_project]
set_property parent.project_path F:/yingjian/verilog/book/theMainDesign/myKeyBoard/myKeyBoard.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  F:/yingjian/verilog/book/theMainDesign/myKeyBoard/myKeyBoard.srcs/sources_1/new/HexToDec.v
  F:/yingjian/verilog/book/theMainDesign/myKeyBoard/myKeyBoard.srcs/sources_1/new/debouncer.v
  F:/yingjian/verilog/book/theMainDesign/myKeyBoard/myKeyBoard.srcs/sources_1/new/Display.v
  F:/yingjian/verilog/book/theMainDesign/myKeyBoard/myKeyBoard.srcs/sources_1/new/PS2Receiver.v
  F:/yingjian/verilog/book/theMainDesign/myKeyBoard/myKeyBoard.srcs/sources_1/new/main.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/yingjian/verilog/book/theMainDesign/myKeyBoard/myKeyBoard.srcs/constrs_1/new/myKeyBoardX.xdc
set_property used_in_implementation false [get_files F:/yingjian/verilog/book/theMainDesign/myKeyBoard/myKeyBoard.srcs/constrs_1/new/myKeyBoardX.xdc]


synth_design -top main -part xc7a100tcsg324-1


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
